# Default values for distributed-jmeter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
dev: true

master:
  ## The number of pods in the master deployment
  replicaCount: 1

server:
  ## The number of pods in the server deployment
  replicaCount: 3

image:
  ## The tag for the image
  ## ref: https://hub.docker.com/r/pedrocesarti/jmeter-docker/tags/
  tag: 5.0
