apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
    helm.sh/chart: {{ include "distributed-jmeter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      role: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        role: server
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ if .Values.dev }} {{ .Release.Name }} {{ else }} wdias/{{ .Release.Name }} {{ end }}
          imagePullPolicy: {{ if .Values.dev }} Never {{ else }} Always {{ end }}
          args: ["server"]
          ports:
            - containerPort: 50000
            - containerPort: 1099
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: module
                operator: In
                values:
                - test
          - weight: 1
            preference:
              matchExpressions:
              - key: datatype
                operator: NotIn
                values:
                - grid
